### ISSUE TITLE
Vehicle Entity Error

### ISSUE THREAD

**Issue by 8BallBomBom** [vercas/vON#1]
If you try to serialize a vehicle entity then you will get malformed errors.
Seems to be due to vehicle entities coming up as Vehicle instead of Entity.
Unsure if any other types of entities have this issue as i haven't checked.

**Comment by vercas** [comment]
Can you add me on Steam to test the fix?
http://steamcommunity.com/profiles/76561198055261787/

**Comment by vercas** [comment]
Fixed. Thank you for all the help! :+1:
