### ISSUE TITLE
Selling work that contains vON

### ISSUE THREAD

**Issue by Partixel** [vercas/vON#4]
So, basically, made a gmod addon, selling it on scriptfoder for money

Just basically want to know if I am allowed to include vON in the zip if I give you full credit for vON on the addons page / in its README?

Or must I remove it and have them download it manually?

**Comment by vercas** [comment]
From what you're telling me, the conditions are met so you are free to redistribute it with you addon, commercially.

**Comment by Partixel** [comment]
Great, thanks for confirming!
