### ISSUE TITLE
von refuses to decode this string, leaves no error/info

### ISSUE THREAD

**Issue by ghost** [vercas/vON#5]
```
~"statusv":n1;"codev":"ZYZ5Yv"  
```

Staying on von stable 1.1.1 (for compatibility with wiremod)

von.deserialize simply returns a table with 5 elements, tried the same with latest von, same result

**Comment by vercas** [comment]
Does it happen with latest vON?

**Comment by ghost** [comment]
http://i.imgur.com/tYAvIy6.png

So it does appear to work but the latest Garry's Mod does not print it correctly, if you copy and paste it this is the result

] lua_run_cl PrintTable(von.deserialize("~\"statusv\":n1;\"codev\":\"ZYZ5Yv\""))
                                                                                    code    =   ZYZ5Y
                                                                                    status  =   1

**Comment by vercas** [comment]
It's because you have a **;** in there. The console thinks you've got 2 commands, fails to parse the second one and drops the commands silently.
